version: "3.7"

services:
  nginx:
    image: nginx:1.25.2
    container_name: "clean_nginx"
    ports:
      - "80:80"
      - "443:443"
    links:
      - mariadb
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ../sockdata:/sock:rw
      - ../src/:/var/www/html # Also map nginx.conf inside the container
      - ../images/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../images/nginx/etc/nginx/mime.types:/etc/nginx/mime.types
      - ../images/nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ../images/nginx/etc/nginx/certs/nginx.crt:/etc/nginx/certs/nginx.crt
      - ../images/nginx/etc/nginx/certs/nginx.key:/etc/nginx/certs/nginx.key
      - ../images/php/8.2/usr/local/etc/php/php.ini:/usr/local/etc/php/php.ini
      - ../images/php/8.2/usr/local/etc/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ../images/php/8.2/usr/local/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf

  phpfpm:
#    image: php:8.2-fpm-alpine
#    image: php:8.2-fpm-bullseye
    image: markoshust/magento-php:8.2-fpm-develop

    container_name: "clean_phpfpm"
    links:
      - mariadb
    volumes: *appvolumes
    ports:
      - "22:22"
    expose:
      - 9000
      - 9001
      - 9003
    extra_hosts:
      - "host.internal.docker:host-gateway"

  mariadb:
    image: mariadb:11.1.2
    container_name: "clean_mariadb"
    command:
      --max_allowed_packet=2048M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
      --max-heap-table-size=12288M
      --join-buffer-size=20485760
    ports:
      - "3306:3306"
    env_file: env/mariadb.env
    volumes:
      - ../mysql-dbdata/:/var/lib/mysql

  redis:
    image: redis:7.2.1-alpine
    container_name: "clean_redis"
    ports:
      - "6379:6379"

  opensearch:
    image: opensearchproject/opensearch:2.11.0
    container_name: "clean_opensearch"
    ports:
      - "9200:9200"
      - "9300:9300"
    env_file: env/opensearch.env
    environment:
      - "discovery.type=single-node"
      ## Avoid test failures due to small disks
      ## More info at https://github.com/markshust/docker-magento/issues/488
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "index.blocks.read_only_allow_delete"

  rabbitmq:
    image: rabbitmq:3.12.6
    container_name: "clean_rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    env_file: env/rabbitmq.env

  mailcatcher:
    image: sj26/mailcatcher
    container_name: "clean_mailcatcher"
    ports:
      - "1080:1080"

  ngrok:
    # Here we can find the external address https://dashboard.ngrok.com/cloud-edge/endpoints
    # Here we can see the authentication token https://dashboard.ngrok.com/get-started/your-authtoken
    image: ngrok/ngrok:3
    container_name: "clean_ngrok"
    ports:
      - 4040:4040
    expose:
      - 4040
    links:
      - nginx
    environment:
      NGROK_AUTHTOKEN: "authtoken_authtoken"
    command: 'http nginx:443'

volumes:
  rabbitmqdata:
  sockdata:
